"""
" service name
"""
SLAM_SERVICE_NAME = "slam_operate"


"""
" service api version
"""
SLAM_API_VERSION = "1.0.0.1"


"""
" api id
"""
SLAM_API_ID_START_MAPPING = 1801
SLAM_API_ID_END_MAPPING = 1802
SLAM_API_ID_INITIALIZE_POSE = 1804
SLAM_API_ID_POSE_NAVIGATION = 1102
SLAM_API_ID_PAUSE_NAVIGATION = 1201
SLAM_API_ID_RESUME_NAVIGATION = 1202
SLAM_API_ID_CLOSE_SLAM = 1901